# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qa_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'qa_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10qa_service.proto\x12\x0bqa_pipeline\"`\n\rMessageDetail\x12(\n\trole_type\x18\x01 \x01(\x0e\x32\x15.qa_pipeline.RoleType\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\"d\n\x16ProcessQuestionRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\x12,\n\x08messages\x18\x03 \x03(\x0b\x32\x1a.qa_pipeline.MessageDetail\"v\n\x17ProcessQuestionResponse\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\x18\n\x10\x64uration_seconds\x18\x02 \x01(\x01\x12,\n\x08messages\x18\x03 \x03(\x0b\x32\x1a.qa_pipeline.MessageDetail*K\n\x08RoleType\x12\x10\n\x0cUNKNOWN_ROLE\x10\x00\x12\x08\n\x04USER\x10\x01\x12\r\n\tASSISTANT\x10\x02\x12\n\n\x06SYSTEM\x10\x03\x12\x08\n\x04TOOL\x10\x04\x32s\n\x11QAPipelineService\x12^\n\x0fProcessQuestion\x12#.qa_pipeline.ProcessQuestionRequest\x1a$.qa_pipeline.ProcessQuestionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qa_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROLETYPE']._serialized_start=353
  _globals['_ROLETYPE']._serialized_end=428
  _globals['_MESSAGEDETAIL']._serialized_start=33
  _globals['_MESSAGEDETAIL']._serialized_end=129
  _globals['_PROCESSQUESTIONREQUEST']._serialized_start=131
  _globals['_PROCESSQUESTIONREQUEST']._serialized_end=231
  _globals['_PROCESSQUESTIONRESPONSE']._serialized_start=233
  _globals['_PROCESSQUESTIONRESPONSE']._serialized_end=351
  _globals['_QAPIPELINESERVICE']._serialized_start=430
  _globals['_QAPIPELINESERVICE']._serialized_end=545
# @@protoc_insertion_point(module_scope)
